
---
# file: roles/base/tasks/git.yml

- name: Add git PPA for latest security patches
  apt_repository:
    # codename was added based on the question found on StackOverflow here
    # https://stackoverflow.com/questions/54283390/ansible-modules-not-working-for-adding-a-git-ppa-wgpg-error-no-pubkey-err
    repo: 'deb https://ppa.launchpadcontent.net/git-core/ppa/ubuntu/ {{ ansible_lsb.codename }} main'
    state: present
    update_cache: True
  become: yes

- name: Install git
  become: yes
  apt:
    name: git 
    state: latest

- name: Setup git config
  file:
    src: $HOME/dotfiles/ansible/roles/base/files/git/gitconfig
    dest: $HOME/.gitconfig
    state: link
