---
# file: roles/base/tasks/main.yml

- include_tasks: bash.yml
- include_tasks: apt-packages.yml
- include_tasks: tmux.yml
- include_tasks: git.yml
- include_tasks: ssh.yml
# - include_tasks: rust.yml
- include_tasks: go.yml
- include_tasks: npm.yml
- include_tasks: rkhunter.yml
- include_tasks: neovim.yml
