#!/usr/bin/env bash

# only try to install sway packages if on a personal computer
if is_work_computer; then
	echo "skipping sway setup"
	return
fi

sway_packages_to_install=(
	"sway"
	"light"        # brightness changes
	"swaylock"     # lockscreen setup
	"waybar"       # status bar
	"rofi"         # app selector
	"wl-clipboard" # clipboard base
	"jq"           # json processor for wayshot
	"grim"         # part of screenshot taking as a part of wayshot
	"slurp"        # part of screenshot taking as a part of wayshot
	"pactl"
	"pulseaudio-utils" # sound changes
  # make sure wlroots and its portal is installed
	"xdg-desktop-portal-wlr"
	"wlroots"
)

install_missing "${sway_packages_to_install[@]}"

# clipboard manager
go_install_package "go.senan.xyz/cliphist" "cliphist"

ensure_folder_symlink_is_in_place "$DOTFILES/rofi" "$XDG_CONFIG_HOME/rofi"
ensure_folder_symlink_is_in_place "$DOTFILES/sway" "$XDG_CONFIG_HOME/sway"
ensure_folder_symlink_is_in_place "$DOTFILES/waybar" "$XDG_CONFIG_HOME/waybar"
ensure_folder_symlink_is_in_place "$DOTFILES/environment.d" "$XDG_CONFIG_HOME/environment.d"
ensure_folder_symlink_is_in_place "$DOTFILES/xdg-desktop-portal" "$XDG_CONFIG_HOME/xdg-desktop-portal"
ensure_file_symlink_is_in_place_as_sudo "$DOTFILES/ssdm/autologin.conf" "/etc/sddm.conf.d/autologin.conf"

