#!/usr/bin/env bash

# setup the bash and terminal related files

declare -A bash_related_file_symlink_info=(
	["$HOME/dotfiles/bash/bashrc"]="$HOME/.bashrc"
	["$HOME/dotfiles/bash/hushlogin"]="$HOME/.hushlogin" # make sure that certain logs are not shown on startup
)

for file in "${!bash_related_file_symlink_info[@]}"; do
	ensure_file_symlink_is_in_place "$file" "${bash_related_file_symlink_info[$file]}"
done

# Install packages
install_missing grep curl fzf btop python3 python3-pip rename ShellCheck bat just make

# Install personal packages on personal computers
if ! is_work_computer; then
	install_missing imgp evince               # pdf editor and viewer
fi

# alias batcat to bat for easier use
batAliasPath="/usr/bin/batcat"
[ ! -f "$batAliasPath" ] && ensure_file_symlink_is_in_place "$batAliasPath" "$HOME/.local/bin/bat"

# source exports so later on we have all of our env variables ready to go
# shellcheck source=./bash/bashrc
source "$HOME/.bashrc"

# create xdg file paths after we have sourced the bashrc to make sure they exist

[ -d "$XDG_DATA_HOME" ] || mkdir -p "$XDG_DATA_HOME"
[ -d "$XDG_CONFIG_HOME" ] || mkdir -p "$XDG_CONFIG_HOME"
[ -d "$XDG_STATE_HOME" ] || mkdir -p "$XDG_STATE_HOME"
[ -d "$XDG_CACHE_HOME" ] || mkdir -p "$XDG_CACHE_HOME"

ensure_file_symlink_is_in_place "$DOTFILES/bash/inputrc" "$INPUTRC"

ensure_file_symlink_is_in_place "$DOTFILES/btop/btop.conf" "$XDG_CONFIG_HOME/btop/btop.conf"
ensure_folder_symlink_is_in_place "$DOTFILES/btop/themes/" "$XDG_CONFIG_HOME/btop/themes"

bat cache --build

# only configure personal computer settings on personal computers
if is_work_computer; then
	return
fi

# gtk-3.0
gtk_config_dir="$XDG_CONFIG_HOME/gtk-3.0"
[ -d "$gtk_config_dir" ] || mkdir -p "$gtk_config_dir"

ensure_file_symlink_is_in_place "$DOTFILES/gtk-3.0/settings.ini" "$gtk_config_dir/settings.ini"
ensure_folder_symlink_is_in_place "$DOTFILES/gtk-3.0/themes" "$HOME/.themes"
