#!/usr/bin/env bash

# only try to install sway packages if on a personal computer
if is_work_computer; then
	echo "skipping sway setup"
	return
fi

sway_packages_to_install=(
	"sway"
	"light"        # brightness changes
	"swaylock"     # lockscreen setup
	"waybar"       # status bar
	"rofi"         # app selector
	"wl-clipboard" # clipboard base
	"jq"           # json processor for wayshot
	"grim"         # part of screenshot taking as a part of wayshot
	"slurp"        # part of screenshot taking as a part of wayshot
)
for pkg in "${sway_packages_to_install[@]}"; do install_apt_package "$pkg"; done

install_apt_package "pactl" "pulseaudio-utils" # sound changes

# clipboard manager
go_install_package "go.senan.xyz/cliphist" "cliphist"

# make sure wlroots and its portal is installed
install_apt_package_by_package_name_only "wlroots"
install_apt_package_by_package_name_only "xdg-desktop-portal-wlr"

ensure_folder_symlink_is_in_place "$DOTFILES/sway" "$XDG_CONFIG_HOME/sway"
ensure_folder_symlink_is_in_place "$DOTFILES/waybar" "$XDG_CONFIG_HOME/waybar"
ensure_folder_symlink_is_in_place "$DOTFILES/environment.d" "$XDG_CONFIG_HOME/environment.d"
ensure_folder_symlink_is_in_place "$DOTFILES/xdg-desktop-portal" "$XDG_CONFIG_HOME/xdg-desktop-portal"
