# $HOME/.bashrc
#
# this file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output. So make sure this doesn't display
# anything or bad things will happen !

# test for an interactive shell. There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
  # shell is non-interactive. be done now!
  return
fi

# ~/.local_exports can be used for other settings you don’t want to commit but that includes the required export values for before the other files.
[ -r "$HOME/.local_exports" ] && [ -f "$HOME/.local_exports" ] && source "$HOME/.local_exports";

# load all files from dotfiles/.shellrc/bashrc.d directory
if [ -d $HOME/dotfiles/.shellrc/bashrc.d ]; then
  for file in $HOME/dotfiles/.shellrc/bashrc.d/*.sh; do
    source $file
  done
fi

# load all files from dotfiles/.shellrc/rc.d directory
if [ -d $HOME/dotfiles/.shellrc/rc.d ]; then
  for file in $HOME/dotfiles/.shellrc/rc.d/*.sh; do
    source $file
  done
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# Append to the Bash history file, rather than overwriting it
shopt -s histappend;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
  shopt -s "$option" 2> /dev/null;
done;

# set keyboard layout to English international to allow alt+character to have accented or Spanish characters

setxkbmap -layout us -variant intl

# start SSH for Github if it has not already started
sshstart

# set nvm version to use and export if it exists already
if [ -d "$HOME/.nvm" ] ; then
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  nvmforceuse $NVM_VERSION
fi

# gvm setup if possible
[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"

gvmforceuse $GO_VERSION

# ~/.localrc can be used for other settings you don’t want to commit and it is loaded last.
[ -r "$HOME/.localrc" ] && [ -f "$HOME/.localrc" ] && source "$HOME/.localrc";

# clear the terminal after the setup is over
c
