# file: local.yml
- name: Set up local workstation
  hosts: local
  # pre_tasks:
  #   - name: Get computer type
  #     hipchat:
  #       color: purple
  #       token: "{{ hipchat_token }}"
  #       room: "{{ hipchat_room }}"
  #       msg: "[Start] Run 'foo/setup.yml' playbook on {{ ansible_nodename }}."
  vars:
    computer_type: "{{ lookup('env','COMPUTER_TYPE') }}"
    user_home: "{{ lookup('env','HOME') }}"
    dotfiles: "{{ lookup('env','HOME') }}/dotfiles/"
  
  roles:
    - role: base
      tags:
        - base
    - role: personal
      when: computer_type == 'personal'
      tags:
        - personal
