
---
# file: roles/base/tasks/syncthing.yml

- name: Add syncthing apt repository key.
  become: true
  get_url:
    url: 'https://syncthing.net/release-key.gpg'
    dest: /usr/share/keyrings/syncthing-archive-keyring.gpg
    mode: '0644'
    force: true

- name: Add syncthing PPA for latest security patches
  apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable'
    state: present
    update_cache: True
  become: yes

- name: Install syncthing
  become: yes
  apt:
    name: syncthing
    state: present 
