
---
# file: roles/personal/tasks/wkhtmltopdf.yml

- name: Check if wkhtmltopdf is installed
  shell: command -v wkhtmltopdf>/dev/null 2>&1
  register: wkhtmltopdf_exists
  ignore_errors: yes
  changed_when: "wkhtmltopdf_exists.rc == 1"

- name: Download and unarchive file
  when: wkhtmltopdf_exists.rc == 1
  unarchive:
    src: https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
    dest: '{{user_home}}/Downloads/'
    remote_src: yes

- name: Copy wkhtmltopdf binaries to their proper location
  when: wkhtmltopdf_exists.rc == 1 
  copy:
    src: "{{ item }}"
    dest: "{{user_home}}/.local/bin/"
  with_fileglob:
    - "{{user_home}}Downloads/wkhtmltox/bin/wkhtmlto*"

- name: Install wkhtmltopdf dependencies and pandoc 
  become: yes
  apt:
    name:
      - openssl
      - libssl-dev
      - libxrender-dev
      - libx11-dev
      - libxext-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - fontconfig
      - pandoc # document conversion
    state: present 
