name: Lint Files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install apt dependencies
        run: |
          sudo apt update
          sudo apt install -y shellcheck shfmt
      - name: Install just
        uses: extractions/setup-just@v2
      - name: Verify installation
        run: |
          shellcheck --version
          shfmt --version
          just --version
      - name: Lint Bash Files
        run: |
          just lint
        